package co.edu.usbcali.abet;
// Generated 31/08/2015 10:03:06 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Estudiante  implements java.io.Serializable {


     private Long idCodigoEstudiante;
     private String nombre;
     private String direccion;
     private String telefono;
     private String email;
     private Set<ListaSepia> listaSepias = new HashSet<ListaSepia>(0);
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);

    public Estudiante() {
    }

	
    public Estudiante(Long idCodigoEstudiante) {
        this.idCodigoEstudiante = idCodigoEstudiante;
    }
    public Estudiante(Long idCodigoEstudiante, String nombre, String direccion, String telefono, String email, Set<ListaSepia> listaSepias, Set<Evaluacion> evaluacions) {
       this.idCodigoEstudiante = idCodigoEstudiante;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.listaSepias = listaSepias;
       this.evaluacions = evaluacions;
    }
   
    public Long getIdCodigoEstudiante() {
        return this.idCodigoEstudiante;
    }
    
    public void setIdCodigoEstudiante(Long idCodigoEstudiante) {
        this.idCodigoEstudiante = idCodigoEstudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<ListaSepia> getListaSepias() {
        return this.listaSepias;
    }
    
    public void setListaSepias(Set<ListaSepia> listaSepias) {
        this.listaSepias = listaSepias;
    }
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }




}


