package co.edu.usbcali.abet;
// Generated 31/08/2015 10:03:06 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OutcomePorPrograma generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class OutcomePorPrograma  implements java.io.Serializable {


     private Long idOutcomePorPrograma;
     private Outcome outcome;
     private Programa programa;
     private Set<RubricaPorCurso> rubricaPorCursos = new HashSet<RubricaPorCurso>(0);

    public OutcomePorPrograma() {
    }

	
    public OutcomePorPrograma(Long idOutcomePorPrograma) {
        this.idOutcomePorPrograma = idOutcomePorPrograma;
    }
    public OutcomePorPrograma(Long idOutcomePorPrograma, Outcome outcome, Programa programa, Set<RubricaPorCurso> rubricaPorCursos) {
       this.idOutcomePorPrograma = idOutcomePorPrograma;
       this.outcome = outcome;
       this.programa = programa;
       this.rubricaPorCursos = rubricaPorCursos;
    }
   
    public Long getIdOutcomePorPrograma() {
        return this.idOutcomePorPrograma;
    }
    
    public void setIdOutcomePorPrograma(Long idOutcomePorPrograma) {
        this.idOutcomePorPrograma = idOutcomePorPrograma;
    }
    public Outcome getOutcome() {
        return this.outcome;
    }
    
    public void setOutcome(Outcome outcome) {
        this.outcome = outcome;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public Set<RubricaPorCurso> getRubricaPorCursos() {
        return this.rubricaPorCursos;
    }
    
    public void setRubricaPorCursos(Set<RubricaPorCurso> rubricaPorCursos) {
        this.rubricaPorCursos = rubricaPorCursos;
    }




}


