package co.edu.usbcali.abet;
// Generated 31/08/2015 10:03:06 PM by Zathura powered by Hibernate Tools 3.2.4.GA



/**
 * Pensum generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Pensum  implements java.io.Serializable {


     private Long idPensum;
     private Programa programa;
     private Materia materia;
     private String semestre;
     private String creditos;

    public Pensum() {
    }

	
    public Pensum(Long idPensum) {
        this.idPensum = idPensum;
    }
    public Pensum(Long idPensum, Programa programa, Materia materia, String semestre, String creditos) {
       this.idPensum = idPensum;
       this.programa = programa;
       this.materia = materia;
       this.semestre = semestre;
       this.creditos = creditos;
    }
   
    public Long getIdPensum() {
        return this.idPensum;
    }
    
    public void setIdPensum(Long idPensum) {
        this.idPensum = idPensum;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(String creditos) {
        this.creditos = creditos;
    }




}


