package co.edu.usbcali.abet;
// Generated 31/08/2015 10:03:06 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RubricaPorCurso generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class RubricaPorCurso  implements java.io.Serializable {


     private Long idRubricaPorCurso;
     private OutcomePorPrograma outcomePorPrograma;
     private Curso curso;
     private Rubrica rubrica;
     private Set<Assesment> assesments = new HashSet<Assesment>(0);

    public RubricaPorCurso() {
    }

	
    public RubricaPorCurso(Long idRubricaPorCurso) {
        this.idRubricaPorCurso = idRubricaPorCurso;
    }
    public RubricaPorCurso(Long idRubricaPorCurso, OutcomePorPrograma outcomePorPrograma, Curso curso, Rubrica rubrica, Set<Assesment> assesments) {
       this.idRubricaPorCurso = idRubricaPorCurso;
       this.outcomePorPrograma = outcomePorPrograma;
       this.curso = curso;
       this.rubrica = rubrica;
       this.assesments = assesments;
    }
   
    public Long getIdRubricaPorCurso() {
        return this.idRubricaPorCurso;
    }
    
    public void setIdRubricaPorCurso(Long idRubricaPorCurso) {
        this.idRubricaPorCurso = idRubricaPorCurso;
    }
    public OutcomePorPrograma getOutcomePorPrograma() {
        return this.outcomePorPrograma;
    }
    
    public void setOutcomePorPrograma(OutcomePorPrograma outcomePorPrograma) {
        this.outcomePorPrograma = outcomePorPrograma;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Rubrica getRubrica() {
        return this.rubrica;
    }
    
    public void setRubrica(Rubrica rubrica) {
        this.rubrica = rubrica;
    }
    public Set<Assesment> getAssesments() {
        return this.assesments;
    }
    
    public void setAssesments(Set<Assesment> assesments) {
        this.assesments = assesments;
    }




}


