package co.edu.usbcali.abet;
// Generated 31/08/2015 10:03:06 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rubrica generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class Rubrica  implements java.io.Serializable {


     private Long idRubrica;
     private String nombreRubrica;
     private Set<RubricaPorCurso> rubricaPorCursos = new HashSet<RubricaPorCurso>(0);
     private Set<DetalleRubrica> detalleRubricas = new HashSet<DetalleRubrica>(0);
     private Set<Categoria> categorias = new HashSet<Categoria>(0);

    public Rubrica() {
    }

	
    public Rubrica(Long idRubrica) {
        this.idRubrica = idRubrica;
    }
    public Rubrica(Long idRubrica, String nombreRubrica, Set<RubricaPorCurso> rubricaPorCursos, Set<DetalleRubrica> detalleRubricas, Set<Categoria> categorias) {
       this.idRubrica = idRubrica;
       this.nombreRubrica = nombreRubrica;
       this.rubricaPorCursos = rubricaPorCursos;
       this.detalleRubricas = detalleRubricas;
       this.categorias = categorias;
    }
   
    public Long getIdRubrica() {
        return this.idRubrica;
    }
    
    public void setIdRubrica(Long idRubrica) {
        this.idRubrica = idRubrica;
    }
    public String getNombreRubrica() {
        return this.nombreRubrica;
    }
    
    public void setNombreRubrica(String nombreRubrica) {
        this.nombreRubrica = nombreRubrica;
    }
    public Set<RubricaPorCurso> getRubricaPorCursos() {
        return this.rubricaPorCursos;
    }
    
    public void setRubricaPorCursos(Set<RubricaPorCurso> rubricaPorCursos) {
        this.rubricaPorCursos = rubricaPorCursos;
    }
    public Set<DetalleRubrica> getDetalleRubricas() {
        return this.detalleRubricas;
    }
    
    public void setDetalleRubricas(Set<DetalleRubrica> detalleRubricas) {
        this.detalleRubricas = detalleRubricas;
    }
    public Set<Categoria> getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Set<Categoria> categorias) {
        this.categorias = categorias;
    }




}


